### ISSUE TITLE
Support multiple tenant identifiers

### ISSUE THREAD

**Issue by benfoster** [saaskit/saaskit#1]
A fairly common scenario (that we ourselves have to cater for at fabrik) is that a tenant may have multiple hostnames mapped to the application.

The tenant resolve interface should support returning additional identifiers when a tenant is resolved so that we do not resolve duplicate instances.

It would also be beneficial to maintain some heirarchy of identifiers so that it would be possible to redirect to a primary url (or perform some other action) should the primary identifier not be used.

**Comment by brgrz** [comment]
Would it make sense for you to rename RequestIdentifiers to something more sensible like RegisteredHostnames?

With regards to hierarchy, would it just make sense to have say one of the registered hostnames is Primary? You don+t actually do redirects hierarchially, do you?

**Comment by benfoster** [comment]
I don't want to rule out the possibility of using other request properties for tenant identification. For example, you may want to build some internal APIs that use a separate port number per tenant.

I agree with regard to the primary identifier. It's unlikely (in the case of hostnames) that you'll want more than one primary.
