### ISSUE TITLE
Crash when TenantResolver returns a null Tenant

### ISSUE THREAD

**Issue by andyward** [saaskit/saaskit#11]
Using nuget 0.0.2pre it's not possible to return `null` in a resolver's `ResolveAsync` method - e.g. where no Tenant can be located. Returning null causes a NullReferenceException in TenantResolutionMiddleware.cs. 

Easily reproduced in the MVC Sample project

**Comment by devployment** [comment]
You can return a null `TenantContext` like this

```return Task.FromResult<TenantContext<AppTenant>>(null);```

This will work and you can handle the `null` tenant in your app logic as needed.

**Comment by benfoster** [comment]
@andyward does that solve the issue? I've added a new [page to the wiki](https://github.com/saaskit/saaskit/wiki/Handling-unresolved-Tenants) that covers this and updated the MVC sample.

**Comment by andyward** [comment]
Thanks. I overlooked the generic ```Task.FromResult``` 

The approach in the wiki works well too.
