### ISSUE TITLE
Api Controller TTenant Always null

### ISSUE THREAD

**Issue by mvanhelmont** [saaskit/saaskit#13]
When i use the following code in a api controller then the tenant will be always null also in the Sample Code

```
public IHttpActionResult Get()
        {
            var tenant = Request.GetTenant<AppTenant>();
            return Ok(tenant);
        }
```

**Comment by mvanhelmont** [comment]
I have found the problem and it's not a real problem in saaskit but more in the behavior of win..

You need to setup saaskit before you setup the webapi in startup.cs then it works

**Comment by benfoster** [comment]
Yes, the order in which you register your middleware is important. The WebAPI OWIN adapter ends the pipeline.
