### ISSUE TITLE
thanks alot for specific solution, I think Needed cache management 

### ISSUE THREAD

**Issue by kanpinar** [saaskit/saaskit#16]
My tenants are stored in db. first load read al from db. When upddated refresh cache
i need to do.
As i could understand there is not a way to do that.

regards 
ans thnks alot again ..

**Comment by benfoster** [comment]
SaasKit provides [caching support](https://github.com/saaskit/saaskit/wiki/Caching-Tenants) but it's pretty basic right now as you can't control the `CacheItemPolicy` used to cache instances. 

For now, you can get access to the cache instance used by the `CachedTenantResolver` like so:

```
MemoryCache cache = new MemoryCache("SaasKit.Tenants");
```

You can then call [cache.Remove](https://msdn.microsoft.com/en-us/library/system.runtime.caching.memorycache.remove(v=vs.110).aspx) providing you know the cache key used by the tenant instance.

Are you using Sql Server? If so you could implement your own version of `CachedTenantResolver` that makes use of [SqlChangeMonitor](https://msdn.microsoft.com/en-us/library/system.runtime.caching.sqlchangemonitor(v=vs.110).aspx).

**Comment by kanpinar** [comment]
Nope using mysql and Identity 2.0
I solved by clearing cache.

regards.
