### ISSUE TITLE
Strong named assemblies support

### ISSUE THREAD

**Issue by hbulens** [saaskit/saaskit#18]
I think the title describes the issue pretty good. 

For my client's commercial software, I'd like to try out SaaSKit as it closely matches my own multi tenant structure, but we are using strong named assemblies so that'd require strong named assemblies for SaaSKit as well.

**Comment by rdefreitas** [comment]
@hbulens, are you certain that Strong Names are a good idea for your client as you target Asp.NET Core?
Remember, these are useful for identity, not security... and with Asp.net Core you should no longer be relying on the GAC.

- https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md
- https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/oss-signing.md

**Comment by benfoster** [comment]
I have no plans to support strong naming.
