### ISSUE TITLE
Support strongly typed tenant instances

### ISSUE THREAD

**Issue by benfoster** [saaskit/saaskit#2]
It would be useful if `TenantInstance` and `ITenantResolver` were generic types so that we could pass a strongly typed tenant object.

**Comment by brgrz** [comment]
Hey Ben, your comments on the above PR from @kether667?

**Comment by benfoster** [comment]
It's unlikely it will get merged in as is. I had already spiked out strongly typed support and the implementation is slightly different. Also, no tests.

**Comment by benfoster** [comment]
`ITenantResolver` is now generic so you can use your own Tenant types.
