### ISSUE TITLE
Sample

### ISSUE THREAD

**Issue by CMTietgen** [saaskit/saaskit#20]
I tried to look at your Mvc sample, but the link it broken. Can you fix it?

https://github.com/saaskit/saaskit/tree/dev/samples/SaasKit.Multitenancy.Samples.Mvc

**Comment by benfoster** [comment]
That link is for the old version of SaasKit which targeted Mvc 5. If you want this check out the [0.0.2 branch](https://github.com/saaskit/saaskit/tree/0.0.2-pre) otherwise for ASP.NET Core have a look in the Samples folder.
