### ISSUE TITLE
Tenant IoC support

### ISSUE THREAD

**Issue by benfoster** [saaskit/saaskit#3]
The ability to scope dependencies per tenant, ideally container agnostic.

**Comment by brgrz** [comment]
Wouldn't this require that we do dependency configuration per tenant, seems to me a bit of an overkill..

**Comment by benfoster** [comment]
@brgrz scoping dependencies per tenant is absolutely fundamental in building multi-tenant applications.

**Comment by brgrz** [comment]
What kind of dependencies do you have in mind?

**Comment by benfoster** [comment]
Probably the most common would be something like database connections / sessions e.g. Session Factory for NHibernate, DBContext for EF and DocumentSession for RavenDB.

It should be possible to build applications that are completely unaware of multi-tenancy simply by scoping dependencies per tenant.

**Comment by benfoster** [comment]
This will be implemented for ASP.NET 5.
