### ISSUE TITLE
AspNetCore RC2: Kestrel server won't bind to multiple server.urls

### ISSUE THREAD

**Issue by ariesdane** [saaskit/saaskit#30]
The server is not honoring  server url bindings when launching web apps using .Net Core RC2 VS tools, eg this doesn't work:

```
var host = new WebHostBuilder()
	.UseKestrel()
	.UseContentRoot(Directory.GetCurrentDirectory())
	.UseUrls("http://localhost:60000", "http://localhost:60002")
	.UseIISIntegration()
	.UseStartup<Startup>()
	.Build();

host.Run();
```

However, everything works fine when launching this way:

```project-root > dotnet run```

I've been digging around, and can't find much on this topic other than a few related issues:

- https://github.com/aspnet/Announcements/issues/174
- http://stackoverflow.com/questions/34212765/how-do-i-get-the-kestrel-web-server-to-listen-to-non-localhost-requests

I tried moving the urls to a server.urls variable in an external hosting.json file and using the configuration builder as suggested in the 2nd link, but that's not working either.

```
var config = new ConfigurationBuilder()
	.SetBasePath(Directory.GetCurrentDirectory())
	.AddJsonFile("hosting.json", optional: true)
	.Build();

var host = new WebHostBuilder()
	.UseKestrel()
	.UseConfiguration(config)
	.UseContentRoot(Directory.GetCurrentDirectory())         
	.UseIISIntegration()
	.UseStartup<Startup>()
	.Build();
	
host.Run();

//  contents of hosting.json, 
// {
//   "server.urls": "http://localhost:60000 http://localhost:60002"
// }
```

The hosting.json file is located in the project root along side project.json and was created based on the only example I could find: 

- https://docs.asp.net/en/latest/fundamentals/servers.html)

Although seemlingly promising, that didn't work either.Are you having this issue too or has anyone else reported it? 

I'm using 1.0.0-preview1-002702.

**Comment by benfoster** [comment]
Are you running one of the samples or is this your own application? I did have this issue during the RC2 upgrade but just made the IIS Url in project properties the same as one of my configured URLs in Startup.cs e.g. `http://localhost:60000`.

**Comment by benfoster** [comment]
I just tested this myself. You need to separate your URLs with a semi-colon:

```
{
  "server.urls": "http://localhost:60000;http://localhost:60001"
}
```

**Comment by ariesdane** [comment]
I cloned a copy of your RC2 dev Saaskit and have the same issue. 

**Step by Step of how I reproduced:**

- Cloned your R2 branch locally
- Opened the solution file in VS2015 
- Set AspNetMvcSample as the startup project
- Build the solution to restore library dependencies
- Launched the AspNetMvcSample inside VS2016 using the "Run" button

**Notes:** 

- I did not make any changes to the project's code or settings
- VS Launch profile was set to IIS Express 
- Launch Settings url was http://localhost:60000

**Results:**

Everything seemed to work fine. The databases were created and Tenant1 loaded up on port 60000.

However, when I attempted to navigate to http://localhost:60002, the browser just spins hopelessly and the host never responds which results in "Page cannot be displayed" error. 

Also, there is zero indication of traffic to the host on port 60002 - the debug console logs nothing and nothing is returned to the browser by the host. 

**Using the dotnet Tool:**

 `dotnet run `  Works, sort of.

- Both http://localhost:6000 and http://localhost:60002 it resolves, as do the other ports. 
- However, the debugger has to be manually attached.
- Db connection "integrated security" no longer works

It's possible it's just my environment causing the host resolution issue, but I'm sure what part. Here's what I'm running:

- IISExpress, v10.0.10557.1000
- Visual Studio, v14.0.25123-update2
- Microsoft .Net Core RC2 Runtime, v1.0.2072
- Microsoft .Net Core RC2 SDK, v1.0.2072
- Microsoft .Net Core RC2 VS 2015 Tooling, v1.0.20513.14-preview1
- Microsoft .Net , v4.6.01038

**More Notes:** 

When launching the application using VS IISExpress profile, the following hack will cause the other ports to be resolved by the host, and you can see activity in the debug console this way. However, the host summarily rejects the request because of a pairing token check being done in the IISExtensions.

```
var host = new WebHostBuilder()
		.UseKestrel()
		.UseContentRoot(Directory.GetCurrentDirectory())
		.UseUrls("http://localhost:60000", "http://localhost:60001", "http://localhost:60002", "http://localhost:60003")
		.UseIISIntegration()
		.UseStartup<Startup>()
		.Build();

 
var hack =  host.ServerFeatures.Get<IServerAddressesFeature>();

hack.Addresses.Add("http://localhost:60001/");
hack.Addresses.Add("http://localhost:60002/");

host.Run();

/*
Browsing to http://localhost:60000 
Ok

Browsing to  http://localhost:60002 

Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware:Error: 'MS-ASPNETCORE-TOKEN' does not match the expected pairing token
*/
```

That error message is produced by the IIS Middleware. However, before the hack nothing happened at all. 

Here's where the error is being thrown in AspNetCore's IISMiddleware:

```
//  Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.cs
//  Lines 58 - 63
// 
            if (!string.Equals(_pairingToken, httpContext.Request.Headers[MSAspNetCoreToken], StringComparison.Ordinal)) 
            { 
                _logger.LogTrace($"'{MSAspNetCoreToken}' does not match the expected pairing token '{_pairingToken}', skipping {nameof(IISMiddleware)}."); 
                 await _next(httpContext); 
                 return; 
             }           

```

**Link to IISMiddleware.cs**

https://github.com/aspnet/IISIntegration/blob/9e6dc5b2dab4e4efc6e2fc331a65cd768ae59627/src/Microsoft.AspNetCore.Server.IISIntegration/IISMiddleware.cs

**Comment by ariesdane** [comment]
I'm going to close this issue. It's not related to SaasKit, and it's easy enough to fix by doing the following:

1. Open the solution's `\.vs\config\applicationhost.config ` file
2. Manually add the additional entries to the site's `<bindings></bindings>` 

**Before**
```
<bindings>
   <binding protocol="http" bindingInformation="*:60000:localhost" />
</bindings>
```

**After**
```
<bindings>
   <binding protocol="http" bindingInformation="*:60000:localhost" />
   <binding protocol="http" bindingInformation="*:60001:localhost" />
   <binding protocol="http" bindingInformation="*:60002:localhost" />
   <binding protocol="http" bindingInformation="*:60003:localhost" />
   <binding protocol="http" bindingInformation="*:60004:localhost" />
</bindings>
```

**Comment by rdefreitas** [comment]
It's an issue with IIS Express, and yes, changing ApplicationHost.config is the way to resolve it.
