### ISSUE TITLE
Support for .Net Core 1.0

### ISSUE THREAD

**Issue by sadjadbp** [saaskit/saaskit#36]
Please add support for .Net Core 1.0, on my end I've tried and it's just changing the project.json and it will compile just fine. Thanks for your time

**Comment by joeaudette** [comment]
"SaasKit.Multitenancy": "1.1.3-*" works just fine on 1.0 RTM

**Comment by sadjadbp** [comment]
@joeaudette I got a runtime dependency error. Download the code and changed project.json, recompiled and everything was fine

**Comment by joeaudette** [comment]
I think the master branch has not yet been updated, the dev branch and the nuget are updated to RTM

**Comment by benfoster** [comment]
Master branch has been updated with the 1.1.3 release.
