### ISSUE TITLE
 Unable to resolve service for type 'Tenant' while attempting to activate 'HomeController'.

### ISSUE THREAD

**Issue by threevaluelogic** [saaskit/saaskit#46]
Hi,

I get the following error which I am really struggling to nail down.
`
Unable to resolve service for type 'Tenant' while attempting to activate 'HomeController'.`

I can see my code enters the TenantResolver successfully which does in fact return a Tenant but when it comes for DI to inject it into my controller it complains with the error listed.

Are there any further steps I am missing to debug?

Thanks,

**Comment by SilverioMiranda** [comment]
In your controller you need TenantContext<Tenant> , not Tenant direct

Like : 

```
public class HomeController
    {
        public HomeController(TenantContext<AppTenant> tenantContext)
        {

        }
    }
```
