### ISSUE TITLE
Issue with tooling preview 2 for .net core 1.0.1

### ISSUE THREAD

**Issue by alandillon** [saaskit/saaskit#49]
It worked before I installed preview 2. Now I get the below issues.

![image](https://cloud.githubusercontent.com/assets/3331097/19278738/7284a1b6-8fac-11e6-98bd-57612e9788ec.png)

![image](https://cloud.githubusercontent.com/assets/3331097/19278767/93c127f0-8fac-11e6-9264-9bfdf5ff53bc.png)

**Comment by benfoster** [comment]
Now upgraded to .Net Core 1.1 - see dev branch.
