### ISSUE TITLE
Default Tenant Instance

### ISSUE THREAD

**Issue by benfoster** [saaskit/saaskit#5]
So that SaasKit can even be used in single-tenant scenarios, a default tenant instance should always be provided so you can use the library OOTB.

This could be done by providing an "Always matching" `ITenantResolver` on the current `SaasKitConfiguration`.

It should also be possible to override the "default" tenant or provide a fallback in multi-tenant scenarios i.e. if no other tenants match, use "this" one.

**Comment by brgrz** [comment]
If we base tenants on hostnames, then you either host a certain hostname as a tenant (and correctly redirect to it) or you don't. If you don't then the correct thing to do is issue 404.

If a client entered our SaaS app hosts in their DNS and later canceled the subscription (so we removed them from our app) but left DNS records pointing to us, we issue 404, we don't redirect them to default tenant.

**Comment by benfoster** [comment]
This can now be handled with the [appropriate middleware](https://github.com/saaskit/saaskit/wiki/Handling-unresolved-Tenants)
