### ISSUE TITLE
UserStore multitenancy

### ISSUE THREAD

**Issue by vdecristofaro** [saaskit/saaskit#52]
I am wondering whether it is possible to use `saaskit `with asp net identity in such a way that each tenant has its own user store.

I have created a custom user store in a way that is somewhat similar to this [blog post](https://www.scottbrady91.com/ASPNET-Identity/Quick-and-Easy-ASPNET-Identity-Multitenancy). However I am using AspNet Identity Core. 

Any suggestion?

**Comment by joeaudette** [comment]
I think it could be done by dependency injection per tenant as in this [blog post by Ben Foster](http://benfoster.io/blog/asp-net-core-dependency-injection-multi-tenant), using different dbcontexts and connection strings per tenant.

If you don't mind using the same db for all tenants, I have an implementation here with tenant aware user and role stores: https://github.com/joeaudette/cloudscribe

**Comment by vdecristofaro** [comment]
Indeed I am using a single database for all tenants.
Let me better explain my scope.
I am trying to build a standalone multitenant identity server setup which is able to authorize users and clients of multiple tenants.
On the clients I am using saaskit to handle hostname tenant identification and pass the tenant name on the acr_values parameter.
On the server I need to figure out:
- the tenant name
- inject the tenant name on the custom user store 
  Actually these are the points where I am most confused.

**Comment by joeaudette** [comment]
using saaskit you should be able to inject the current tenant anywhere you need it, just add it to the constructor wherever you need to access it and it should get injected

**Comment by vdecristofaro** [comment]
@joeaudette
Do you mean thai I should use Saaskit on the server as well?

**Comment by joeaudette** [comment]
> I am trying to build a standalone multitenant identity server setup which is able to authorize users and clients of multiple tenants.

to do that yes, unless all the client tenants use the same set of users. 
if by "IdentityServer" you mean [IdentityServer4](https://github.com/IdentityServer/IdentityServer4) you may find my solution interesting https://github.com/joeaudette/cloudscribe.StarterKits/tree/master/cloudscribe-idserver-ef

**Comment by vdecristofaro** [comment]
I have watched your solution and it is certainly interesting.
Yes I am talking about that Identity server.
I my case however, I am sending the tenant from the client, which receive it from hostname, in acr_values.

How do I get the tenant from acr_values? As fair as I know this can be done in the authorize endpoint but that would be too late and initialization has already been done. 
I am sorry if those appear to be dumb questions to you, maybe they are, or are simply the results of my confusion.

**Comment by joeaudette** [comment]
sorry those questions are over my head, I don't know what acr_values is, i'm fairly new to IdentityServer4.

I have a multi-tenant solution for the IdentityServer itself with support for the first folder segment in the url used to determine the tenant.

If I were trying to make a multi tenant api to be protected by the corresponding tenants of the identity server, I would use saaskit to branch the middleware on the api and configure each api tenant to point to the correct authority url for the identityserver tenant. I have not tried that yet but pretty sure it would work. So far I've created different api apps protected by different identityserver tenants.

for client mvc apps, again I think the same approach of branching the middleware and using different urls for the identityserver authority endpoint is what I would do

**Comment by vdecristofaro** [comment]
Ok. So in your case you have multiple clients (mvc and api) and a single identity server which you fork at startup to setup on each URL fragment.

In my case is slightly different. I have a single identity server with an identity implementation which is multitenant enabled. In this setup, every client, as in your case, identifies the tenant and send it to identity server together with the request and the ef implementation is able to authorize the client/user as per the corresponding tenant database data.

Thanks however for your support, it is always interesting to share thoughts and ideas. Moreover I discovered cloudscribe which deserve a look.

**Comment by papyr** [comment]
The code is here mostly, this would be sooo much nicer to have an Admin page that can add roles, users, tenants... as well in the ASP MVC 5 version.
