### ISSUE TITLE
SaasKit.Multitenancy.Mvc Not found

### ISSUE THREAD

**Issue by partharanjan** [saaskit/saaskit#54]
Hi,
I am new to SaasKit and wants to use my MVC 5 application.

When trying to add this package I am getting below error
PM> Install-Package SaasKit.Multitenancy.Mvc
Install-Package : Unable to find package 'SaasKit.Multitenancy.Mvc'
At line:1 char:1
+ Install-Package SaasKit.Multitenancy.Mvc
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

Can you please help me how to add mvc package into my application.

**Comment by faizalshap** [comment]
I also did the same and got the Error. I guess its removed or something. Lets hope @benfoster adds it again. :)

**Comment by benfoster** [comment]
```
Install-Package SaasKit.Multitenancy.Mvc -Version 0.0.2-pre -Pre
```
