### ISSUE TITLE
Does SaasKit support loading routes per tenant?

### ISSUE THREAD

**Issue by brgrz** [saaskit/saaskit#55]
The above question also relates a lot to the ability to load modularized parts of code with SaasKit per tenant as these modules would also bring with them controllers with attribute routes defined.

**Comment by vandensd** [comment]
Also looking for something similar. Especially to prepare middleware for URL rewrites. The resolve should optionally occur during the middleware pipeline so that we can inject the tenant for certain logic.

**Comment by benfoster** [comment]
There's nothing built in to SaasKit but given that almost every .NET core component supports DI, you should be able to customise routing accordingly and inject the tenant. Unfortunately I don't have an example of this but would love for someone to contribute one.
