### ISSUE TITLE
Does not compile with latest ASP MVC core - dependecy issues

### ISSUE THREAD

**Issue by papyr** [saaskit/saaskit#59]
Hi, I was trying to run the samples with the current ASP MVC Core release (latest) and it would not compile, it seems there are many dependency issues that the nuget is not able to resolve.

Since there were quite a few, I was not able to resolve the dependencies myself can you  please update nugets and check-in .

thanks
Papy

**Comment by benfoster** [comment]
I'll try and get out a new release ASAP

**Comment by papyr** [comment]
hi Ben, since the code is here mostly, this would be sooo much nicer to have an Admin page that can add roles, users, tenants... as well in the ASP MVC 5 version. Many of us are using the ASP MVC 5 version till the Core 1 is fully baked in!

**Comment by benfoster** [comment]
Unfortunately this is beyond the scope of SaasKit as the definition of a tenant will vary too much between developers.
