### ISSUE TITLE
Resolving Tenants in ReBus

### ISSUE THREAD

**Issue by robvanpamel** [saaskit/saaskit#62]
Hi, 

We are working on a project which is using Rebus. Since we are already using SaasKit for tenant resolution for the HTTP Context we have created a first rough implementation which is able to resolve tenants based on Rebus in stead of HTTP. This could come in handy for other developers as well. 

At this moment Saaskit is build directly on the HttpContext, but if we can abstract this further we can create different implementations. 
- Http implementation 
- Rebus implementation
- ...

If you are interested in this, we could work this out, but their will be some major changes in the project structure. 

At this moment the biggest change is that the TenantResolver is using an Object as parameter 

`
      public interface ITenantResolver<TTenant>
      {
        Task<TenantContext<TTenant>> ResolveAsync(object context);
      }
` 

Afterwards the correct context is choosen. 
You can see more details at https://github.com/robvanpamel/saaskit 

Kind regards
  Rob

**Comment by shawnmclean** [comment]
I'm also looking into rolling out a tenant resolver on other non web platforms, like a service or console. I'm thinking of wrapping that parameter in a proxy or something else. I just don't like the design of having an object param.

**Comment by robvanpamel** [comment]
So you would create a separate interface which is then implemented in the
the httpcontext--wrapper and the message contract-wrapper? And afterwards
make the tenant resolver work with the interface, correct?



Op wo 18 jan. 2017 om 04:52 schreef Shawn Mclean <notifications@github.com>

**Comment by benfoster** [comment]
I don't have any immediate plans for this - but if you'd like to post more details of what would be involved, please go ahead.
