### ISSUE TITLE
UsePerTenant and Authentication

### ISSUE THREAD

**Issue by dguinn-oncore** [saaskit/saaskit#63]
Hi Ben -

Saaskit is amazing!  Following your examples, I've been able to make almost everything work, with the exception of multi-tenant authentication using the "UsePerTenant" extension with OIDC.  

When I start the app, it lands on the home page fine (auth not required) but when I hit a controller method decorated with [Authorize], I get the following error:

> System.InvalidOperationException: No authentication handler is configured to handle the scheme: Automatic

Here is the "configure" method from my startup:

     public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
     {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseStaticFiles();

            app.UseMultitenancy<AppTenant>();
            app.UsePerTenant<AppTenant>((ctx, builder) =>
            {
                app.UseCookieAuthentication(new CookieAuthenticationOptions
                {
                    AuthenticationScheme = $"{ctx.Tenant.Id}.Cookies",
                    AutomaticAuthenticate = true,
                    AutomaticChallenge = true,
                    SlidingExpiration = true,
                    CookieName = $"{ctx.Tenant.Id}.AspNet.Cookies"
                });

                JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
                app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
                {
                    AuthenticationScheme = "oidc",
                    SignInScheme = $"{ctx.Tenant.Id}.Cookies",
                    Authority = "http://localhost:5555",
                    RequireHttpsMetadata = false,
                    ClientId = ctx.Tenant.Hostname,
                    ClientSecret = "secret",
                    ResponseType = "code id_token",
                    Scope = { "openid", "profile", "roles", "mtt_webapi", "offline_access" },
                    GetClaimsFromUserInfoEndpoint = true,
                    SaveTokens = true,
                    TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
                    {
                        NameClaimType = "name",
                        RoleClaimType = "role"
                    }
                });
            });

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
      }

Any advice you could give would be largely appreciated.  I'm at a loss.

Thanks!

**Comment by benfoster** [comment]
It doesn't look like you've defined a scheme called Automatic. Your schemes
are oidc and [TenantId].Cookies.

Can you post your controller code?

**Comment by dguinn-oncore** [comment]
Hi Ben,

Thanks for the response.  Sure, here you go.  Nothing really to it, just the default HomeController with the "Contact" view set up to demonstrate switching tenant connectionstrings and the "About" view set up to show the user claims.

    public class HomeController : Controller
    {
        TestAppContext _dbContext;
        public HomeController(TestAppContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult About()
        {
            ViewData["Message"] = "Your security claims.";
            return View(new ViewAboutModel
            {
                 Claims = User.Claims.ToList()
            });
        }

        public async Task<IActionResult> Contact()
        {
            ViewData["Message"] = "Your favorite foods.";
            var foods = await _dbContext.Foods.ToListAsync();
            return View(new ViewContactModel
            {
                FavoriteFoods = foods
            });
        }

        public IActionResult Error()
        {
            return View();
        }
    }

    public class ViewContactModel
    {
        public List<Food> FavoriteFoods { get; set; }
    }

    public class ViewAboutModel
    {
        public List<Claim> Claims { get; set; }
    }

Thanks again!

**Comment by dguinn-oncore** [comment]
For anyone who runs into this same problem, I figured out it was because I used "app.*" in the UsePerTenant block instead of "builder.*", so it was as if no authentication was being defined at all!
