### ISSUE TITLE
Could not create a model binder for model object of type 'SaasKit.Multitenancy.ITenant

### ISSUE THREAD

**Issue by dewebeloper** [saaskit/saaskit#64]
Hi
I have very odd issue. I implement SaasKit example in my project and when I try to inject AppTenant in HomeController  I get issue: 
`InvalidOperationException: Could not create a model binder for model object of type 'SaasKit.Multitenancy.ITenant`1[Core.Multitenancy.AppTenant]'.`

In my HomeController  I have ctor like:
`public IActionResult Index(ITenant<AppTenant> tenantt)`

If I put 
`public IActionResult Index(AppTenant tenantt)`
then I don't get issue, but all tenant properties are null.

I can confirm that AppTenantResolver are able to resolve tenant and put object in TenantContext.
Also, on request, in Startup.Configure, in context I'm able to see selected tenant in Context.Items, with all values.

In ConfigureServices I have
`services.AddMultitenancy<AppTenant, CachingAppTenantResolver>();`
and
```
services.Configure<RazorViewEngineOptions>(options =>
{
   options.ViewLocationExpanders.Add(new TenantViewLocationExpander());
});
services.Configure<MultitenancyOptions>(Configuration.GetSection("Multitenancy"));
```
in Configure

`app.UseMultitenancy<AppTenant>();`

after app.UseStaticFiles(); and before app.UseMvc

Any idea what can be wrong?
Thanks.

**Comment by dguinn-oncore** [comment]
HI dewebeloper, just from the code above, it seems like you are not properly injecting the Tenant (it's generally advised to do this in the constructor, though there are other ways), you are just using it as an argument...  You need to do something like this:

    public class HomeController : Controller
    {
        private readonly TestAppContext _dbContext;
        private readonly AppTenant _currentTenant;
 
        public HomeController(TestAppContext dbContext, ITenant<AppTenant> tenant)
        {
            _dbContext = dbContext;
            _currentTenant = tenant;
        }

        public IActionResult Index()
        {
            ViewData["Message"] = $"Welcome to {_currentTenant.TenantName}.";
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }

If you really need to inject into the method as an argument, I think you can use the [FromServices] tag in front of the argument name, but I've never actually used that.

Good luck!

**Comment by dewebeloper** [comment]
With eyes but still blind man, that's me :).
Of course that I need ctor to resolve DI. 
Thanks and sorry I bothered you with this.
Cheers
