### ISSUE TITLE
Dbcontext Migration not working sue to AppTenant Null

### ISSUE THREAD

**Issue by learntecno** [saaskit/saaskit#65]
The below code is not working , The  AppTenant is null in the SqlServerApplicationDbContext constructor.
please help he how to fix this issue.

using (var serviceScope = app.ApplicationServices.GetRequiredService<iservicescopefactory>()
.CreateScope())
{
serviceScope.ServiceProvider.GetService<sqlserverapplicationdbcontext>()
.Database.Migrate();
}

**Comment by TFleury** [comment]
I think that `TenantPipelineMiddleware` should replace `ApplicationBuilder`'s `ApplicationServices` with tenant's container services.

**Comment by benfoster** [comment]
If you're running your migration outside of the HTTP request (e.g. from Visual Studio) then the tenant will always be null. I suggest posting this issue in the gitter channel as I'm not that familiar with EF migrations.

**Comment by learntecno** [comment]
Thank you, yes it is not possible outside of the HTTP request , we have to manually instantiate AppTenant for generation Migration
