### ISSUE TITLE
Dynamic Tenant Registration

### ISSUE THREAD

**Issue by grahamehorner** [saaskit/saaskit#66]
Please consider the option of allowing dynamic tenant registration; my thoughts on the implementation would be to create a TenantResolver that uses a DistributedCache (allowing support for web farms) together with adding a new TenantRegisteration service to dependency injection, this service would/could then be used by a mvc view/controller update the backend persistent store and/or the DistributedCache with regards to tenant details and the endpoints (hostnames) for the tenant.

**Comment by ErickSGM** [comment]
Our team case is a little different, but I think it also applies on dynamic tenant registration. We have a tenant server which fires events on tenant creation/update/delete, then each service pulls its relevant information and caches it locally. I'm working with the idea of creating a custom tenant resolver that pulls from that cache. I'm working currently in this feature. I forked the project and i'm upgrading the csproj and structuremap dependencies and will try this idea soon.

**Comment by benfoster** [comment]
Given that tenants are lazily initialised, dynamic registration is implicitly supported. Perhaps I'm missing your requirements?
