### ISSUE TITLE
nuget package

### ISSUE THREAD

**Issue by luisrudge** [saaskit/saaskit#7]
this project needs a nuget package :)

**Comment by brgrz** [comment]
@benfoster Despite our chat on twitter, I still think we should push this project on, OWIN seems ok for it and it'll be easily upgradable to ASP.NET 5 when released. Also ASP.NET 5, as it stand now, won't introduce anything remotely related to tenant management, hence this project seems fine and won't get obsolete.

As such, I think we should issue prerealse Nuget packages to Nuget feed. Did you have any specific thoughts on how you want to do it?

**Comment by benfoster** [comment]
FYI, I'll be releasing Nuget packages in a few weeks. Should be pushing up a new version of the multitenancy support next week.

**Comment by benfoster** [comment]
Now on nuget as a pre-release package. https://www.nuget.org/packages/SaasKit.Multitenancy/
