### ISSUE TITLE
Redirection not working properly

### ISSUE THREAD

**Issue by rpundlik** [saaskit/saaskit#70]
Hi All,
I am trying to redirect to my controllers action method if tenant not found or in case of 404 error.
But redirection is going in loop only, I am using TenantUnresolved middleware.
It goeus to redirect method of middleware and then again goes to resolve the client and again redirect and so on
why this issue is occurring ?
Any help on this appreciated

**Comment by benfoster** [comment]
Please see the updated sample at https://github.com/saaskit/saaskit/tree/dev/samples/AspNetMvcSample.

If you're still experiencing this issue, please add more details.
