### ISSUE TITLE
Sample code works only for one tenant

### ISSUE THREAD

**Issue by mkgn** [saaskit/saaskit#75]
The sample code works for only one tenant. Ex:- localhost:60000 works. But if i enter Tenant 2 url: localhost:60002 it just says unable to connect. It doesn't break in TenantResolver either.

I haven't change a single line of code. 

Am I doing something wrong?

**Comment by benfoster** [comment]
Which sample project are you running?

**Comment by mkgn** [comment]
It's AspNetMvcSample.

In the downloaded code, by default it's set to use SqlLiteContext. I
changed it to SQLServer and when run under port:60000, the db for Tenant1
is getting created and all is fine.

However if I try with port:60002 which is Tenant2, it says unable to
connect.

Should I configure something else?

Thanks/

**Comment by mkgn** [comment]
Any input on this?

**Comment by benfoster** [comment]
Does it work for you with SQLite?

**Comment by mkgn** [comment]
Sorry man,

I was on vacation for few days... hibernated :) . Yep got it to work! I have missed the URL configuration part!

All works fine. There is another advice needed but I will add it as a separate thread so others might also find it useful.
