### ISSUE TITLE
[Idea] - scrap tenant resolver middleware

### ISSUE THREAD

**Issue by dazinator** [saaskit/saaskit#77]
Just an idea that I ended up implementing recently myself and seemed to work quite well. Consider this middleware: https://github.com/saaskit/saaskit/blob/master/src/SaasKit.Multitenancy/Internal/TenantResolutionMiddleware.cs

You can scrap this middleware entirely if:

1. Replace it with a "scoped" service, that does exactly what the middleware does, but in a `Lazy<TTenant>` such that the tenant is lazily resolved on first access of the Tenant property / method.

I think this then simplifies things a bit because:

1. TenantResolutionMiddleware can be dropped meaning less step for consumer.
2. People can inject the `ITenantAccessor` service whenever they need to access current Tenant (rather than inject `TenantContext` or `TTenant.`
3. You can change the implementation of ITenantAccessor so that it doesn't need to store the TenantContext in httpcontext - because its already a scoped service, it can just keep the TenantContext directly as a property. This means you could also remove the extensions methods for httpcontext that Get / Set the TenantContext from httpcontext - as it would no longer be stored there - it would be held on the ITenantAccessor, which unlike the middleware, is accessible anywhere the tenant needs to be accessed.

**Comment by RickBlouch** [comment]
I do think the middleware concept is nice from a logging perspective to see which tenant (and other data) was resolved (for me from a database or distributed cache) prior to the request being dumped into MVC.  Every request in my app requires this tenant data so for us it makes sense to load and validate it up front.

That being said, I could see us writing the middleware that I described which just uses ITenantAccessor. 

ITenantAccessor could also have a property bag outside of TenantContext that we could use for same request caching instead of using HttpContext.  We currently do this for some infrequently used but expensive data elements that should not live in TenantContext, but we do not want to compute twice on the same request.

**Comment by dazinator** [comment]
> We currently do this for some infrequently used but expensive data elements that should not live in TenantContext, but we do not want to compute twice on the same request

Im curios, are you avoiding tenant context for storage because it doesnt play well with distributes cache? Or is there another reason?

If you want to ensure some exoensive state is only loaded once, and only when its needed, per request, then im not sure why you dont register a scoped service in the container that provides that state as a lazy.

If you wanted to change the scope of that state to be once per tenant (and  not just once per http request) you could keep everything as is but just register it in the tenants container instead. I guess I am just struggling to see the perks of the property bag approach to this, but im probably missing something.

**Comment by RickBlouch** [comment]
> If you want to ensure some exoensive state is only loaded once, and only when its needed, per request, then im not sure why you dont register a scoped service in the container that provides that state as a lazy.

Yes, agreed.  Better separation of concerns at least.  My original thought was to combine the two since they were similar in their scope but a separate scoped service makes more sense overall.

Also, the reason for this data not going into TenantContext is because it's user / workstation / functionality configurations typically based on the specific workflow the user is currently in.  There are hundreds of workflow and config variations and it doesn't make sense to cache them as a unit in TenantContext.  Sometimes we need the config during processing and also in the view, in these cases I just don't want to hit the DB or Redis twice.

**Comment by dazinator** [comment]
In the end, I spiked out my idea: Here is the code with a sample app: https://github.com/dazinator/Dotnettency.git and published nuget packages here: https://www.nuget.org/packages?q=DOTNETTENCY

**Comment by benfoster** [comment]
@dazinator I'm in the process of upgrading SaasKit to csproj and then will look at some of the items we discussed. It would be good if we could incorporate your ideas into SaasKit - I'll have a look through your code tomorrow.

**Comment by dazinator** [comment]
@benfoster - Ok no problem. You should be able to run the sample under kestrel, and hit it on localhost:5000 - 5003 to see how the various tenants behave. Per tenant middleware and Containers seem to be working ok. I will probably add in support for some more containers before I am done (like autofac and ninject).

**Comment by grahamehorner** [comment]
@benfoster @dazinator would be nice if the SaaSKit supported the new asp.net core 2.0 kestrel pipeline as the performance improvement work the asp.net core 2.0 team have done is greate, also there are some breaking changes which may impact the SaasKit functionality

**Comment by benfoster** [comment]
Do you have a link providing more details about this?

**Comment by grahamehorner** [comment]
@benfoster only the standard github/aspnet repo with announcements

**Comment by benfoster** [comment]
@dazinator I've had a look your code - great job! It's certainly given me some ideas on how I can unify some of the SaasKit APIs.

However, I'm not yet sold on dropping the middleware since somewhere along the line you're going to need to await the resolver/accessor and I'd prefer to have the framework do this. Likewise, while I get the reasoning for making this lazy, in practice do you foresee many scenarios where you *won't* want to identify the tenant at the beginning of the request?

**Comment by dazinator** [comment]
Maybe it depends. If staticfiles is added after multitenancy middleware you might be resolving tenant on some requests for no reason.. then again if you are isolating static files somehow per tenant, then in that case you would need to resolve the tenant in advance, it depends on your implementaton. The beauty of lazily resolving it when its needed is that if by chance there is a request where the tenant wasnt needed, you havent bothered resolving it. However the cost of resolution shouldnt be too high anyway (unless the tenant needs to be re-initialised) so I wouldnt expect any saving to be huge but it would free up sone unneeded contention on the cache / concurrent dictionaries.

With the new razor pages stuff, you might have some simple content pages that are common to all tenants, so if that page is requested, you dont necessarily need the tenant to be resolved during that request.

To be honest ive just tried to be flexible here. You could still have the middleware sitting on top of the lazy, but it wouldnt be mandatory that you put it in the pipeline. It could just be optionally used in the pipeline if you know you always want to enforce the tenant resolution at a certain stage regardless of the type of request. I will probably end up calling it `EnforceTenantResolution` middleware or something.

Given that you can directly inject a TTenant where its needed, and resolution happens lazily, im not sure of what the benefits are of enforcing resolution for the sake of it? What are the pro's of that?

**Comment by dazinator** [comment]
One last thing
> since somewhere along the line you're going to need to await the resolver/accessor 

If TTenant is injected directly, the awaiting is handled by the framework at that point. I added that feature so you dont have to inject an ITenanrAccessor and await yourself.

**Comment by benfoster** [comment]
@dazinator can you point me to the code where you're doing that?

**Comment by dazinator** [comment]
Sure. https://github.com/dazinator/Dotnettency/commit/d99c39cb6837d268ebee4721aaa1ff039bc4d8e6

**Comment by benfoster** [comment]
Unfortunately [this](https://github.com/dazinator/Dotnettency/commit/d99c39cb6837d268ebee4721aaa1ff039bc4d8e6#diff-2ca40d9d5177a6292c76e0c5f4df9176R24) is a blocking call which is what I want to avoid.

**Comment by dazinator** [comment]
Yep guilty as charged! :-)
Thinking through that - given that the task is lazy - guessing it would block on the first inject ( assuming it hadnt already been resolved earlier anywhere else in the request?) 

I think I will document that as being a potential side effect when using TTenant injection and not enforcing tenant resolution early on. Thanks for catching this Ben!

**Comment by dazinator** [comment]
I guess in terms of the blocking:

1. Potentially long block if tenant needs to be initialised (very first request on ap start)
2. Small block if: task not yet run (first inject of TTenant for request)
3. No block if: tenant is already resolved.

Think number 1 might be an issue. Number 2 isn't ideal but I can just about live with it given that it should be very small as the fully initialised tenant just needs to be grabbed from cache.

I'm going of this idea now!

**Comment by dazinator** [comment]
I have decided in the end, to still support injection of TTenant, but just document that it has the potential to block. I'll advocate that `ITenantAccessor` should be used for non blocking access to the current tenant and leave it at that!

**Comment by dazinator** [comment]
One other idea if you wanted to be really explicit about it would be to support the inject of `Blocking<TTenant>` which is just a wrapper around the TTenant instance resolved via the potentially blocking Task.Result... Meh.. probably overkill at this stage.

**Comment by dazinator** [comment]
Or even.. allow the `Task<TTenant>` to be injected! BOOM that's the feature I want right there.

**Comment by dazinator** [comment]
Inject `Task<TTenant>` seems to work nicely: https://github.com/dazinator/Dotnettency/commit/a15eaa05566abe7efdef1e3468974da88869fee9#diff-dcaa3e511ec5996c9946ae81b027c8d1R16
