### ISSUE TITLE
[Idea] Tenant file system

### ISSUE THREAD

**Issue by dazinator** [saaskit/saaskit#78]
@benfoster - just wondering if you see any potential value in this concept: https://github.com/dazinator/Dotnettency/issues/10

The main kind of use case I am thinking for it at the moment, is to allow any file (css, cshtml) to be overridden on a per tenant basis, if the file is placed in a certain location. I am working at the IFileProvider level, so I am hoping that MVC etc defers every file request to that! Anyway, if anyone has any feedback on that please let me know.

**Comment by joeaudette** [comment]
@dazinator in my cloudscribe project I'm supporting per tenant .cshtml by using view location expander that prioritizes searching for views first in a per tenant theme, then per tenant Views folder, then default locations.

for static files, I'm supporting per tenant wwwroot folder and per theme wwwroot folder. I do that by branching the static files middleware using saaskit app.UsePerTenant. you can [see my code here](https://github.com/joeaudette/cloudscribe/blob/master/src/cloudscribe.Core.Web/BuilderExtensions.cs)

my filemanager also supports users uploading files into the tenant specific wwwroot folders and sub folders

**Comment by dazinator** [comment]
@joeaudette - interesting, thanks I will take a look!

**Comment by dazinator** [comment]
Rather than configuring lower level services (MVC view expandor) which works for razor views, I thought it would be fun to try and nail this at an even broader level. I'm registering a scoped version of `IHostingEnvironment`, and similar to container middleware, i'm swapping the `ContentRoot` and `WebRoot` file providers out for the current tenant ones, early in the request. This means during a http request, anything that resolves `IHostingEnvironment` to get some content or web file via its file providers will be using ones specific to the current tenant. This means the file paths can remain the same throughout the system (e.g `/skin.css`) but just resolve differently depending on who the tenant is. The file providers I am setting up for each tenant allow each tenant to have its own root directory, as part of a composite which includes the application level root directory - so that each tenant can resolve application level files (ContentRoot / WebRoot) but then if files with the same paths are present in the tenants root directory then they override application level ones. This allows any file to be overriden at a tenant level not just cshtml, by placing a file with the same subpath, in that tenants personal root directory. I have the basics all working
 I am calling this technique `PerTenantHostingEnvironment`. 

I next need to get an MVC sample running - to see how much (if any) of the MVC stack, is utilising the IHostingEnvironment file providers from Request Services. For example, if the razor compilation does this then I shouldnt need a custom view expandor. If however razor resolves the IFileProvider from applicationservices then i'll be stuck because this isn't tenant specific so.. we shall see!

**Comment by dazinator** [comment]
So the main problem I have found so far with this approach is `StaticFiles` middleware, resolves the `IHostingEnvironment` in it's constructor which means its going to resolve it once, irrespective of who the current tenant might be. It then uses the `IFileProvider` from that instance throughout the lifetime of the application.

To workaround this, I think I will have to do the following:

Any middleware that resolves an `IHostingEnvironment` in its constructor (like StaticFiles) I'll have to register in the `per tenant middleware` pipeline - so that each tenant has its own instance of the middleware, with an IHostingEnvironment injected that is approriate for that tenant!

I'll keep battling onwards.

**Comment by joeaudette** [comment]
Somehow trying to override IHostingEnvironment which is designed to be a singleton, per tenant doesn't appeal to me personally.  After all there is only one hosting environment for all the tenants in actuality so trying to spoof it as if they were in different hosting environments seems dubious to me. For my purposes there are actually multiple static resource wwwroot folders per tenant that I am supporting and it seems better to set them up specifically rather than trying to make IHostingEnvironment point to a different single wwwroot folder per tenant.
Not saying it is a bad idea just that it doesn't appeal to me personally. In my case I'm shipping nugets for others to consume in their own apps and hijacking IHostingEnvironment could make IHostingEnvironment behave unexpectedly for the developer consuming my nugets.

**Comment by dazinator** [comment]
Yep I totally get that!

There is indeed really only one hosting environment. Still I'll pursue this a bit longer to see how it turns out as I do believe there will be some benefits. For example, if a controller injects IHostingEnvironment and use an IFileProvider to return a file - there is now no danger of any files for other tenants being accessible. This to me seems like better isolation in a multitenant scenario. Many things up and down the asp.net core stack rely on IHostingEnvironment mainly for its IFileProviders (static files, razor etc) - so it feels (to me) like a nice architectural way to get everything that works with files, to work in way thats isolated to the current tenant.

Still this is probably overkill for most apps, and there are ofcourse going to be other solutions. I'll just see how this pans out though, may be a dead end!

**Comment by dazinator** [comment]
Oh yes.. this is working like a charm. If anyone is interested you can run the "Sample" here: https://github.com/dazinator/Dotnettency/tree/develop/src/Dotnettency.Sample
and then browse to: 

- http://localhost:5001/Index.html
- http://localhost:5002/Index.html
- http://localhost:5003/Index.html

on 5000 and 5001 (Both are tenant BAR) you get this:

![image](https://user-images.githubusercontent.com/3176632/28713866-d240b8c2-7388-11e7-932c-a638cfa7514f.png)

On 5002 (Tenant Foo) you get this: 

![image](https://user-images.githubusercontent.com/3176632/28713886-e702d45c-7388-11e7-85c4-d8d052667a3a.png)

The project structure looks like this - but focus on where Index.html is which demonstrates that the file can be overridden on a per tenant basis (The GUID's are tenant's id's)

![image](https://user-images.githubusercontent.com/3176632/28713742-4b6ef37c-7388-11e7-9214-41988fafdbba.png)

Each tenant gets a composite IFileProvider encapsulating the host level folder, plus its tenant specific one, ie. for tenant foo this is:-

- wwwroot
- wwwroot/.tenants/049c8cc4-3660-41c7-92f0-85430452be22/

Using a period in the folder name i.e `.tenants` ensures its a hidden directory in terms of the first IFileProvider looking at `wwwroot` 

This means tenants can also have files that are only visible for that tenant - they just need to be in the tenant specific folder, and not in the common / host level folder. It also means multiple tenants can have their own version of the same file, without any conflicts as they see the file in isolation. 

![image](https://user-images.githubusercontent.com/3176632/28714079-ae16fd02-7389-11e7-8717-ad6c7a8a96ad.png)

This isn't necessarily anything new or exciting in terms of how IFileProviders work. However in terms of how static files middleware works, all I had to do was add the static files middleware with its vanilla / default configuration (didn't have to configure it's IFileProvider etc) to the tenant middleware pipeline - and now it behaves like this by default. This is because of the use of `UsePerTenantHostingEnvironment` and also #80 

Therefore I would expect all other middlewares to behave similar when added to the per tenant middleware pipeline - i.e they only get a Tenant view of the world. I am going to experiment with an MVC sample next to see what that does in terms of things like razor, view components, etc. In theory I think it means you will be able to override all those things on a per tenant basis too, without having to configure any custom services. 

The same concept also applies to the "Content" file system.. browse on the various ports (5000-5003) on the default url to see a json result which includes the contents of reading a content file on `/Info.txt` - for some tenants `/Info.txt` resolves to the `tenant isolated` file. For others it resolves to the system level (i.e common) file.

I'm closing this for now can open a new issue if saaskit ever wants to implement somehing similar. Otherwise I am happy for this to live in dotnettency.

**Comment by dazinator** [comment]
Oops - forgot to push. Have just pushed the sample now.
